[pytest]
testpaths = test/unit/src/python
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = src/python
addopts = -v --strict-markers
markers =
    unit: Unit tests
    integration: Integration tests
